---

- name: "Install Prometheus"
  hosts: localhost
  gather_facts: true
  become: true
  vars:
    prometheus_targets:
      node:
      - targets:
        - localhost:9100
        labels:
          env: demosite
    node_exporter_tls_server_config:
      cert_file: /etc/node_exporter/tls.cert
      key_file: /etc/node_exporter/tls.key
    node_exporter_basic_auth_users:
      randomuser: examplepassword
    alertmanager_version: latest

  pre_tasks:
    - name: "Download prometheus ansible collection"
      ansible.builtin.shell:
        cmd: "ansible-galaxy collection install prometheus.prometheus"

    - name: Create node_exporter cert dir
      ansible.builtin.file:
        path: "/etc/node_exporter"
        state: directory
        owner: root
        group: root

    - name: Create cert and key
      ansible.builtin.openssl_certificate:
        path: /etc/node_exporter/tls.cert
        csr_path: /etc/node_exporter/tls.csr
        privatekey_path: /etc/node_exporter/tls.key
        provider: selfsigned

  roles:
    - prometheus.prometheus.prometheus
    - prometheus.prometheus.node_exporter
    - prometheus.prometheus.alertmanager

...